# Generated by Django 3.2.5 on 2021-07-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo')),
                ('date', models.DateField()),
                ('tit', models.CharField(max_length=250)),
                ('disc', models.TextField()),
            ],
        ),
    ]
